TARGET_KERNEL_SOURCE := kernel/samsung/a02
TARGET_KERNEL_CONFIG := a02_defconfig
TARGET_KERNEL_ARCH := arm
TARGET_KERNEL_HEADER_ARCH := arm

BOARD_KERNEL_CMDLINE := console=ttyMT0,921600n1 androidboot.hardware=mt6739 printk.devkmsg=on
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_TAGS_OFFSET := 0x07A00000
BOARD_RAMDISK_OFFSET := 0x07C00000
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
