DEVICE_PATH := device/samsung/a02

# ===== Architecture: 32-bit ARM =====
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a53

TARGET_2ND_ARCH :=
TARGET_2ND_ARCH_VARIANT :=
TARGET_2ND_CPU_ABI :=
TARGET_2ND_CPU_ABI2 :=
TARGET_2ND_CPU_VARIANT :=

# ===== Platform =====
TARGET_BOARD_PLATFORM := mt6739
TARGET_BOOTLOADER_BOARD_NAME := a02
TARGET_NO_BOOTLOADER := true

# ===== Kernel =====
TARGET_KERNEL_SOURCE := kernel/samsung/a02
TARGET_KERNEL_CONFIG := a02_defconfig
TARGET_KERNEL_ARCH := arm
BOARD_KERNEL_IMAGE_NAME := zImage

# ===== Partisi (sesuaikan sama layout stok a02 lo) =====
BOARD_BOOTIMAGE_PARTITION_SIZE := 41943040
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 3221225472
BOARD_VENDORIMAGE_PARTITION_SIZE := 536870912
BOARD_USERDATAIMAGE_PARTITION_SIZE := 25000000000
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_COPY_OUT_VENDOR := vendor
BOARD_USES_VENDORIMAGE := true
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# ===== A/B & Treble =====
AB_OTA_UPDATER := false
BOARD_USES_RECOVERY_AS_BOOT := false
PRODUCT_FULL_TREBLE_OVERRIDE := true
BOARD_VNDK_VERSION := current

# ===== Include vendor blobs board config kalau ada =====
-include vendor/samsung/a02/BoardConfigVendor.mk

TARGET_SUPPORTS_32_BIT_APPS := true
TARGET_SUPPORTS_64_BIT_APPS := false
